version: '3.0'

services:
  db:
    image: mysql:8.0
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    restart: always
  backend:
    build:
      context: ./
    ports:
      - '8080:8080'
    expose:
      - '8080'