version: '3.0'

services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    restart: always
  java-program:
    build:
      context: ./jenkins-test.jar
    ports:
      - "8080:8080"